### api test
GET http://localhost:8000

### post new use
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
  "firstName": "anmol",
  "lastName": "bhattarai",
  "email": "anm@anm",
  "password": "asd"
  
}